In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

**1.2**
**Gauss–Jordan Elimination**

In [25]:
def elimination_forward(A):
    def left_most_nonzero_column_ix_jx(A, start_ix, jx):
        for i in range(start_ix, A.shape[0]):
            if A[i, jx] != 0:
                return True, i, jx
            
        if jx < A.shape[1] - 2:
            return left_most_nonzero_column_ix_jx(A, start_ix, jx+1)
        
        else: return False, 0, 0
        
    def interchange_row(A, i1, i2):
        A[[i1, i2]] = A[[i2,  i1]]
        return A
    
    def mul_ix_row_by_inv_ix_jx_term(A, ix, jx):
        A[ix] *= (1 / A[ix, jx])
        return A  
    
    def add_ix_row_to_rows(A, ix, jx):
        for i in range(ix + 1, A.shape[0]):
            if A[i, jx] != 0:
                A[i] += (-1 * A[i, jx]) * A[ix]
        return A
        
    jx = 0
    pivots = []
    for ix in range(A.shape[0]):
        found, ix_containing_one, jx = left_most_nonzero_column_ix_jx(A, ix, jx)
        if not found:
            break
        if ix_containing_one != ix:
            A = interchange_row(A, ix_containing_one, ix)
            
        pivots.append((ix, jx))
        A = mul_ix_row_by_inv_ix_jx_term(A, ix, jx)
        A = add_ix_row_to_rows(A, ix, jx)
        jx += 1
    return A, pivots
    
def elimination_backward(A, pivots):
    while len(pivots) != 0:
        ix, jx = pivots.pop()
        if ix == 0:
            break
        for i in range(0, ix):
            A[i] += (-1 * A[i, jx]) * A[ix]
    return A

In [49]:
arr = np.array([[0, 0, -2, 0, 7, 12,], [2, 4, -10, 6, 12, 28,], [2, 4, -5, 6, -5, -1,]], dtype = float)
print(arr)
forward_arr, pivots = elimination_forward(arr)
elimination_backward(forward_arr, pivots)

[[  0.   0.  -2.   0.   7.  12.]
 [  2.   4. -10.   6.  12.  28.]
 [  2.   4.  -5.   6.  -5.  -1.]]


array([[1., 2., 0., 3., 0., 7.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 2.]])

In [50]:
arr = np.array([[1, 3, -2, 0, 2, 0, 0,],
                [2, 6, -5, -2, 4, -3, -1,],
                [0, 0, 5, 10, 0, 15, 5],
                [2, 6, 0, 8, 4, 18, 6]], dtype = float)
print(arr)
forward_arr, pivots = elimination_forward(arr)
elimination_backward(forward_arr, pivots)

[[ 1.  3. -2.  0.  2.  0.  0.]
 [ 2.  6. -5. -2.  4. -3. -1.]
 [ 0.  0.  5. 10.  0. 15.  5.]
 [ 2.  6.  0.  8.  4. 18.  6.]]


array([[ 1.        ,  3.        ,  0.        ,  4.        ,  2.        ,
         0.        ,  0.        ],
       [-0.        , -0.        ,  1.        ,  2.        , -0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.33333333],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

**1.3 Multiplying Matrices**

In [46]:
def matrix_product(A, B):
    assert A.shape[1] == B.shape[0], f'shapes ({A.shape[0]},{A.shape[1]}) and ({B.shape[0]},{B.shape[1]}) not aligned'
    C = np.zeros((A.shape[0], B.shape[1]))
    
    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            for k in range(A.shape[1]):
                C[i,j] += A[i,k] * B[k,j]
    return C

In [47]:
A = np.array([[2,3,1], [1,2,1]])
B = np.array([[1,1,1], [2,2,2]]).T
matrix_product(A, B)

array([[ 6., 12.],
       [ 4.,  8.]])

In [48]:
A.dot(B)

array([[ 6, 12],
       [ 4,  8]])

In [67]:
def transpos(A):
    AT = np.zeros((A.shape[1], A.shape[0]), dtype = A.dtype)
    for i in range(AT.shape[0]):
        AT[i] = A[:, i]
    return AT

In [68]:
transpos(B)

array([[1, 1, 1],
       [2, 2, 2]])

In [64]:
B.T

array([[1, 1, 1],
       [2, 2, 2]])

In [69]:
def trace(A):
    assert A.shape[0] == A.shape[1], f'({A.shape[0]},{A.shape[1]}) is not a square matrix'
    s = 0
    for i in range(A.shape[0]):
        s += A[i,i]
    return s

In [73]:
trace(np.array([[1,1], [0,2]]))

3